# Site settings
title: Spencer Alexander
description: Software Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spencer Alexander
user_description: I'm a Software Engineer specializing in front-end technologies and development. I'm always looking for a new challenge!
user_title: Software Engineer
email: slalexander92@gmail.com
# twitter_username: lorem_ipsum
github_username:  slalexander92
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
